version: '3'

services:

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    container_name: user-creation-service-container
   
    restart: always
 
    networks:
      - rabbitmq-fanout
    
    depends_on:
      - mongo
    
    volumes:
      - .:/app
      - /app/node_modules
 
   

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mongo-container
    networks:
      - rabbitmq-fanout
    volumes:
      - 'mongoData:/data/db' 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aman
      - MONGO_INITDB_ROOT_PASSWORD=pass123
      - MONGO_INITDB_ROOT_DATABASE=dbuser

networks:
  rabbitmq-fanout:

volumes:
  mongoData:
